[workspace]
authors = ["Qwacktuz <104035252+Qwacktuz@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "QuantCapital"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
pandas = ">=2.3.3,<3"
numpy = ">=2.4.1,<3"
matplotlib = ">=3.10.8,<4"
requests = ">=2.32.5,<3"
jupyter = ">=1.1.1,<2"
python-dotenv = ">=1.2.1,<2"
